export const FORMS_INIT: 'FORMS_INIT' = 'FORMS_INIT'
export const FORMS_COLORS_CHANGE: 'FORMS_COLORS_CHANGE' = 'FORMS_COLORS_CHANGE'
export const FORMS_SIZES_CHANGE: 'FORMS_SIZES_CHANGE' = 'FORMS_SIZES_CHANGE'

export const EXAMPLE_ACTION: 'EXAMPLE_ACTION' = 'EXAMPLE_ACTION'