export const PRODUCTS_INIT: 'PRODUCTS_INIT' = 'PRODUCTS_INIT'
export const PRODUCTS_GET: 'PRODUCTS_GET' = 'PRODUCTS_GET'

export const PRODUCTS_PRICE_FILTER_CHANGE: 'PRODUCTS_PRICE_FILTER_CHANGE' = 'PRODUCTS_PRICE_FILTER_CHANGE'
export const PRODUCTS_MATERIAL_FILTER_CHANGE: 'PRODUCTS_MATERIAL_FILTER_CHANGE' = 'PRODUCTS_MATERIAL_FILTER_CHANGE'
export const PRODUCTS_COLOR_FILTER_CHANGE: 'PRODUCTS_COLOR_FILTER_CHANGE' = 'PRODUCTS_COLOR_FILTER_CHANGE'

export const PRODUCTS_PRICE_CHANGE: 'PRODUCTS_PRICE_CHANGE' = 'PRODUCTS_PRICE_CHANGE'
export const PRODUCTS_MATERIAL_CHANGE: 'PRODUCTS_MATERIAL_CHANGE' = 'PRODUCTS_MATERIAL_CHANGE'
export const PRODUCTS_COLOR_CHANGE: 'PRODUCTS_COLOR_CHANGE' = 'PRODUCTS_COLOR_CHANGE'

export const PRODUCTS_PAGE_CHANGE: 'PRODUCTS_PAGE_CHANGE' = 'PRODUCTS_PAGE_CHANGE'
export const PRODUCTS_LOADING_CHANGE: 'PRODUCTS_LOADING_CHANGE' = 'PRODUCTS_LOADING_CHANGE'