export const PRODUCTS_INIT: "PRODUCTS_INIT" = "PRODUCTS_INIT";
export const PRODUCTS_CHANGE: "PRODUCTS_CHANGE" = "PRODUCTS_CHANGE";

export const PRODUCTS_PRICE_FILTER_CHANGE: "PRODUCTS_PRICE_FILTER_CHANGE" =
  "PRODUCTS_PRICE_FILTER_CHANGE";
export const PRODUCTS_SIZE_FILTER_CHANGE: "PRODUCTS_SIZE_FILTER_CHANGE" =
  "PRODUCTS_SIZE_FILTER_CHANGE";
export const PRODUCTS_COLOR_FILTER_CHANGE: "PRODUCTS_COLOR_FILTER_CHANGE" =
  "PRODUCTS_COLOR_FILTER_CHANGE";
export const PRODUCTS_COLLECTION_FILTER_CHANGE: "PRODUCTS_COLLECTION_FILTER_CHANGE" =
  "PRODUCTS_COLLECTION_FILTER_CHANGE";

export const PRODUCTS_PRICE_CHANGE: "PRODUCTS_PRICE_CHANGE" =
  "PRODUCTS_PRICE_CHANGE";
export const PRODUCTS_SIZE_CHANGE: "PRODUCTS_SIZE_CHANGE" =
  "PRODUCTS_SIZE_CHANGE";
export const PRODUCTS_COLOR_CHANGE: "PRODUCTS_COLOR_CHANGE" =
  "PRODUCTS_COLOR_CHANGE";

export const PRODUCTS_COLLECTION_CHANGE: "PRODUCTS_COLLECTION_CHANGE" =
  "PRODUCTS_COLLECTION_CHANGE";

export const PRODUCTS_PAGE_CHANGE: "PRODUCTS_PAGE_CHANGE" =
  "PRODUCTS_PAGE_CHANGE";
export const PRODUCTS_LOADING_CHANGE: "PRODUCTS_LOADING_CHANGE" =
  "PRODUCTS_LOADING_CHANGE";

export const FETCH_PRODUCTS: "FETCH_PRODUCTS" = "FETCH_PRODUCTS";

export const ADD_TO_FAVORITE: "ADD_TO_FAVORITE" = "ADD_TO_FAVORITE";
export const ADD_TO_CART: "ADD_TO_CART" = "ADD_TO_CART";
